[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[build]
# デフォルトターゲットはネイティブ
# target = "x86_64-unknown-linux-gnu"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true